export const API_ERROR_CODES = [
  "UNAUTHENTICATED",
  "TASK_NOT_FOUND",
  "NOT_AUTHORIZED",
  "INVALID_ARGUMENT",
  "INVALID_TRANSITION",
  "REASON_REQUIRED",
  "TASK_DELETED",
  "TASK_NOT_RECOVERABLE",
  "PARENT_NOT_ELIGIBLE",
  "SUBTASK_DEPTH_EXCEEDED",
  "REMINDER_NOT_FOUND",
  "INVALID_REMINDER_STATE",
  "CONFLICT",
  "INTERNAL",
] as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[number];
